{{ if (eq (.Values.cloud | toString) "gcp" )}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-resizable
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
reclaimPolicy: Retain
#volumeBindingMode: Immediate
allowVolumeExpansion: true
{{- else if (eq (.Values.cloud | toString) "aws") }}
#
# AWS resizable disk example
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-resizable
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
#volumeBindingMode: Immediate
allowVolumeExpansion: true
{{- end }}
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: signoz
spec:
  defaults:
    templates:
      serviceTemplate: chi-service-template
  configuration:
    zookeeper:
      nodes:
        - host: signoz-zookeeper
          port: 2181
      session_timeout_ms: 6000
    clusters:
      - name: cluster
        # Templates are specified for this cluster explicitly
        templates:
          podTemplate: pod-template-with-volume
        layout:
          shardsCount: 1
          replicasCount: 1
    files:
      init-db.sql: |
        CREATE TABLE IF NOT EXISTS signoz_index (
        timestamp DateTime64(9) CODEC(Delta, ZSTD(1)),
        traceID String CODEC(ZSTD(1)),
        spanID String CODEC(ZSTD(1)),
        parentSpanID String CODEC(ZSTD(1)),
        serviceName LowCardinality(String) CODEC(ZSTD(1)),
        name LowCardinality(String) CODEC(ZSTD(1)),
        kind Int32 CODEC(ZSTD(1)),
        durationNano UInt64 CODEC(ZSTD(1)),
        tags Array(String) CODEC(ZSTD(1)),
        tagsKeys Array(String) CODEC(ZSTD(1)),
        tagsValues Array(String) CODEC(ZSTD(1)),
        statusCode Int64 CODEC(ZSTD(1)),
        references String CODEC(ZSTD(1)),
        externalHttpMethod Nullable(String) CODEC(ZSTD(1)),
        externalHttpUrl Nullable(String) CODEC(ZSTD(1)),
        component Nullable(String) CODEC(ZSTD(1)),
        dbSystem Nullable(String) CODEC(ZSTD(1)),
        dbName Nullable(String) CODEC(ZSTD(1)),
        dbOperation Nullable(String) CODEC(ZSTD(1)),
        peerService Nullable(String) CODEC(ZSTD(1)),
        INDEX idx_tagsKeys tagsKeys TYPE bloom_filter(0.01) GRANULARITY 64,
        INDEX idx_tagsValues tagsValues TYPE bloom_filter(0.01) GRANULARITY 64,
        INDEX idx_duration durationNano TYPE minmax GRANULARITY 1
        ) ENGINE MergeTree()
        PARTITION BY toDate(timestamp)
        ORDER BY (serviceName, -toUnixTimestamp(timestamp))

  templates:
    hostTemplates:
      - name: port-distribution
        portDistribution:
          - type: ClusterScopeIndex
        spec:
          tcpPort: 9000
          httpPort: 8123
          interserverHTTPPort: 9009

    podTemplates:
      - name: pod-template-with-volume
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:21.7
              volumeMounts:
                - name: storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: initdb
                  mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: initdb
              configMap:
                name: initdb-config
    serviceTemplates:
      - name: chi-service-template
        generateName: clickhouse-signoz
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: {{ .Values.clickhouseOperator.serviceType }}
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          {{- if (eq (.Values.cloud | toString) "gcp" )}}
          storageClassName: gce-resizable
          {{- else if (eq (.Values.cloud | toString) "aws") }}
          storageClassName: gp2-resizable
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouseOperator.storage | quote }}
